[2025-09-21T13:12:49.791+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-21T13:12:49.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T13:10:38.928925+00:00 [queued]>
[2025-09-21T13:12:49.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T13:10:38.928925+00:00 [queued]>
[2025-09-21T13:12:49.817+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-09-21T13:12:49.825+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2025-09-21 13:10:38.928925+00:00
[2025-09-21T13:12:49.827+0000] {standard_task_runner.py:63} INFO - Started process 140 to run task
[2025-09-21T13:12:49.830+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_streaming_pipeline', 'start_kafka_producer', 'manual__2025-09-21T13:10:38.928925+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/iot_pipeline_dag.py', '--cfg-path', '/tmp/tmpc6ut1wol']
[2025-09-21T13:12:49.832+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask start_kafka_producer
[2025-09-21T13:12:49.842+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-21T13:12:49.862+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T13:10:38.928925+00:00 [running]> on host ad09578b3bc5
[2025-09-21T13:12:49.906+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_streaming_pipeline' AIRFLOW_CTX_TASK_ID='start_kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T13:10:38.928925+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-21T13:10:38.928925+00:00'
[2025-09-21T13:12:49.907+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-21T13:12:49.918+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-21T13:12:49.919+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/*** && python kafka_producer/producer.py']
[2025-09-21T13:12:49.924+0000] {subprocess.py:86} INFO - Output:
[2025-09-21T13:12:49.982+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-21T13:12:49.986+0000] {subprocess.py:93} INFO -   File "/opt/***/kafka_producer/producer.py", line 1, in <module>
[2025-09-21T13:12:49.986+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer, KafkaError
[2025-09-21T13:12:49.987+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-09-21T13:12:49.987+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-21T13:12:49.987+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-21T13:12:49.997+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-21T13:12:50.000+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_streaming_pipeline, task_id=start_kafka_producer, run_id=manual__2025-09-21T13:10:38.928925+00:00, execution_date=20250921T131038, start_date=20250921T131249, end_date=20250921T131250
[2025-09-21T13:12:50.009+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task start_kafka_producer (Bash command failed. The command returned a non-zero exit code 1.; 140)
[2025-09-21T13:12:50.016+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-21T13:12:50.032+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-21T13:12:50.033+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
