[2025-09-21T12:31:05.655+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-21T12:31:05.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:25:59.976153+00:00 [queued]>
[2025-09-21T12:31:05.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:25:59.976153+00:00 [queued]>
[2025-09-21T12:31:05.681+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-21T12:31:05.689+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): start_kafka_producer> on 2025-09-21 12:25:59.976153+00:00
[2025-09-21T12:31:05.692+0000] {standard_task_runner.py:63} INFO - Started process 77 to run task
[2025-09-21T12:31:05.694+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_streaming_pipeline', 'start_kafka_producer', 'manual__2025-09-21T12:25:59.976153+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/iot_pipeline_dag.py', '--cfg-path', '/tmp/tmp1jdl42je']
[2025-09-21T12:31:05.697+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask start_kafka_producer
[2025-09-21T12:31:05.708+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-21T12:31:05.740+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_streaming_pipeline.start_kafka_producer manual__2025-09-21T12:25:59.976153+00:00 [running]> on host b539b7bf4f8a
[2025-09-21T12:31:05.807+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_streaming_pipeline' AIRFLOW_CTX_TASK_ID='start_kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T12:25:59.976153+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-21T12:25:59.976153+00:00'
[2025-09-21T12:31:05.808+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-21T12:31:05.822+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-21T12:31:05.829+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 220, in execute
    raise AirflowException(f"Can not find the cwd: {self.cwd}")
airflow.exceptions.AirflowException: Can not find the cwd: /Users/kabirmathur/Documents/AQI
[2025-09-21T12:31:05.833+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_streaming_pipeline, task_id=start_kafka_producer, run_id=manual__2025-09-21T12:25:59.976153+00:00, execution_date=20250921T122559, start_date=20250921T123105, end_date=20250921T123105
[2025-09-21T12:31:05.841+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task start_kafka_producer (Can not find the cwd: /Users/kabirmathur/Documents/AQI; 77)
[2025-09-21T12:31:05.878+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-21T12:31:05.897+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-21T12:31:05.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
